module.exports = {
  // LOGIN: '/notification/send_otp/', 
  USERLOGIN : '/login',
  LOGIN : '/user/signup',
  CREATE_USER : '/user/create',
  SEND_OTP_PHONE : '/user/send_otp/phone',
  SEND_OTP_EMAIL : '/user/send_otp/email',
  VERIFY_OTP_PHONE: '/user/verify_otp/phone',
  VERIFY_OTP_EMAIL: '/user/verify_otp/email',
  ALIES_EXIST : '/user/is_alias_exist',
  GET_CATEGORIES : '/group/get_categories',
  GENERATE_GROUP : '/group/create',
  GET_SUB_CATEGORIES : '/group/get_sub_categories',
  GET_COMMUNITY : '/group/get_communityV1',
  BELONG_DETAILS : 'group/ (get Api)',
  FOLLOWERS : '/user/follower_list',
  FOLLOWED : '/user/followed_list',
  INVITE : '/group/bulk_user_invite',
  CREATEPOST : '/post/create',
  GET_CURATED_TIMELINE : '/post/get_curated_timeline',
  GET_GROUP_LIST : '/group/get_group_list',
  EXTERNAL_SHARE : '/post/share_externally',
  BOOKMARK_SAVE : '/post/bookmark',
  BOOKMARK_DELETE : '/post/delete_bookmark',
  POST_ALL_REPLIES : '/post/all_replies',
  POST_SEARCH_TIMELINE : '/post/search_timeline',
  POST_CREATE_REPLY : '/post/create_reply',
  GET_CURRENT_USER_NAME : '/user/',
  GET_LEAD_ALL : '/lead/',
  GET_PRODUCT_DETAILS : '/lead_info/',
  GET_FILTER_API : '/lead/filter',
  GET_USER_LIST_API : "/user_list",
  USER_UPDATE_API : '/lead/2'
};
