module.exports = {
  LOGIN: '/notification/send_otp/',
  TRUECALLER: '/auth/truecaller-login/',
  REFRESHTOKEN : '/auth/token-refresh/',
  LOGOUT: '',
  USER: '/auth/shortprofile/',
  RECEIVEOTP: '/notification/send_otp/',
  VERIFYOTP: '/auth/users/otplogin/',
  PACKAGEDETAILS : '/package/data/',
  ALLPHLEBOLIST: '/panel/data/',
  SAMPLEHANDOVER: '/phlebo/sample_handover/',
  EDITSAMPLEHANDOVER: '/phlebo/sample_handover/1/',
  PACKAGES: '/package/crmdata/',
  CITY: '/core/cities/',
  EDITPROFILE: '/auth/users/',
  LEADGENRATION: '/lead/generate-lead-by-user/',
  BANNER: '/blog/banner/',
  CUSTOMERBOOKINGDETAILS: '/booking/customer_booking/',
  DOWNLOAD: '/booking/report_status/',
  PINCODE: '/phlebo/zone-web/',
  MYCART: '/cart/',
  ADDADDRESS: '',
  COUPON: '/coupon/customer-data/',
  ADDRESS: '/auth/address/',
  EDITADDRESS: '/auth/address/',
  BOOKING_SLOT_COLLECTION_DATE: '/booking/booking_slot_collection_date/',
  CREATE_BOOKING:'/booking/customer/create/',
  CART:'/cart/',
  PAYMENT:'/payment/order_payment/',
  PHLEBOLOC:'/booking/phlebo_loc/',
  PLAN_DETAIL:'/package/data_web/',
  PARAMETERS:'/package/pack-parameter/',
  RSIKAREA:'/package/tags/',
  UPLOAD_PRESCREPTION: '/booking/prescription_upload/',
  REDCASH: '/coupon/redcash/',
  REDCASHDETAILS : '/coupon/redcashdetails/',
  MYPRESCREPTION : '/booking/prescription_upload/',
  CENTER : '/center/data/',
  LABS_NETWORK :'/panel/lab_web/',
  GIFTCARD : '/panel/user-from-phone-email/',
  BLOGS_LIST : '/blog/blog_card/',
  BLOG_DETAILS : '/blog/blog/',
  MY_GIFT_CARD : '/coupon/gift_card/',
  CITYLIST     : '/core/displaycities/',
  ALREADY_LOGIN : '/auth/already/',
  // new booking flow
  FAMILY_CART: '/cart/family-cart-list/',
  FAMILYMEMBER : '/cart/family-member/',
  ADDMEMBER : '/cart/add-member/',
  ADD_MEMBER_TO_PACKAGE : '/cart/add-member-to-package/',
  CANCEL_BOOKING : '/booking/customer_booking/',
  SINGLE_BOOKING_DETAILS : '/booking/step_remarks/',
  EDIT_FAMILY_MEMBER : '/cart/edit-member/',
  REMOVE_PACKAGEFROM_CART : '/cart/delete-multiple/',
  REMOVE_MEMBER_FROM_CART : '/cart/remove-member-from-product/',
  ACCESS_TOKEN_MAPMYINDIA : '/panel/mapmyindia-auth-token/',
  CHECK_VALID_ADDESS : '/booking/checking-geofence-area-mapmyindia_2/',
  DELETE_MEMBER : '/cart/delete-member/'
 
};
