module.exports = {
  // LOGIN: '/notification/send_otp/', 
  USERLOGIN : '/user/login',
  LOGIN : '/user/signup',
  CREATE_USER : '/user/create',
  SEND_OTP_PHONE : '/user/send_otp/phone',
  SEND_OTP_EMAIL : '/user/send_otp/email',
  VERIFY_OTP_PHONE: '/user/verify_otp/phone',
  VERIFY_OTP_EMAIL: '/user/verify_otp/email',
  ALIES_EXIST : '/user/is_alias_exist',
  GET_CATEGORIES : '/group/get_categories',
  GENERATE_GROUP : '/group/create',
  GET_SUB_CATEGORIES : '/group/get_sub_categories',
  GET_COMMUNITY : '/group/get_community',
  BELONG_DETAILS : 'group/ (get Api)',
  FOLLOWERS : '/user/follower_list',
  FOLLOWED : '/user/followed_list',
  INVITE : '/group/bulk_user_invite',
  CREATEPOST : '/post/create',
  GET_CURATED_TIMELINE : '/post/get_curated_timeline'
};
